version: '3.8'

services:
    api:
        image: ${DOCKERHUB_USERNAME}/calbak-api:latest
        container_name: calbak-api
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=default
            - DB_URL=${DB_URL}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - JWT_SECRET=${JWT_SECRET}
            - GEMINI_API_KEY=${GEMINI_API_KEY}
            - FRONTEND_URL=${FRONTEND_URL}
            - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
        restart: always
