@base_url = http://localhost:8080
# @base_url = https://calbak.o-r.kr

### 온보딩 추가 정보 입력 API 테스트
### 사전 조건: 구글 로그인 완료 후 access_token 쿠키가 발급된 상태
PATCH {{base_url}}}/api/users/additional-info
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "nickname": "캘박마스터",
    "gender": "MALE",
    "ageGroup": "AGE_20S",
    "job": "대학생,개발자",
    "usagePurpose": "수업 관리,일정 알림",
    "sleepTime": "23:00:00",
    "wakeUpTime": "07:30:00",
    "notificationSetting": "MIN_30"
}
