name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review, edited, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # 리뷰어와 담당자를 수정할 권한이 꼭 필요합니다.
      contents: read
    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          # 앞서 작성하신 설정 파일의 경로를 지정합니다.
          configuration-path: ".github/auto_assign.yml"
